### ISSUE TITLE
Use the "main" field of package.json to locate self plugin

### ISSUE THREAD

**Issue by meteorlxy** [not-an-aardvark/eslint-plugin-self#3]
https://github.com/not-an-aardvark/eslint-plugin-self/blob/7992f65654a1f3a3747aae0a0fcba626b358b803/index.js#L3

It's better to require plugin from `"main"` of `package.json`.

Something like:

```js
const pkg = require('../../package.json');
const plugin = require(path.resolve(__dirname, '../..', pkg.main))
```

**Comment by not-an-aardvark** [comment]
Does the current behavior cause problems in practice? I think loading a directory automatically has the effect of resolving the `main` field of `package.json`.

**Comment by meteorlxy** [comment]
Uh you are right. Something could have gone wrong at the time 😅
